name: Generate Word docs
on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container:
      image: docker://adurnaverden/latex_eisvogel:latest
      options: --entrypoint=sh
    steps:
      - uses: actions/checkout@v2
      - name: prepare output directories
        run: |
          for d in */; do
            mkdir -p output/$d
          done
      - name: convert md to pdf eisvogel
        run: |
          find ./eisvogel -iname '*.md' -type f -exec sh -c 'pandoc ${0} -o output/eisvogel/${0%.md}.pdf --listings --pdf-engine xelatex --template ./templates/eisvogel.tex' {} \;
      - name: convert md to pdf assignment
        run: |
          find ./assignment -iname '*.md' -type f -exec sh -c 'pandoc ${0} -o output/assignment/${0%.md}.pdf --listings --pdf-engine xelatex --template ./templates/assignment.tex' {} \;
      - name: convert md to pdf report
        run: |
          find ./report -iname '*.md' -type f -exec sh -c 'pandoc ${0} -o output/report/${0%.md}.pdf --listings --pdf-engine xelatex --template ./templates/report.tex' {} \;
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
